### ISSUE TITLE
Trouble with rocket league recognizing vJoy devices as controllers

### ISSUE THREAD

**Issue by robot-rover** [drssoccer55/RLBot#11]
Hello, I got all of the scripts up and running, and if I check Monitor vJoy it shows that the vjoy devices' buttons are being pressed, but I cannot get rocket league to recognize the controllers. Can anyone give me some insight?

**Comment by robot-rover** [comment]
So I just saw the Mega Issue thread and went through all of the instructions in there. I installed vjoy and that is working. I ran x360ce in administrator mode and had it autofill the controls for controller 1 & 2. I Opened rocket league and ran p2PressStart.py and I can't get player 2 to join. Player 1 inputs don't register for rocket league either. Anyone know what might be happening. (I just want to add this project looks like it could be super cool!)

**Comment by ddthj** [comment]
Make sure you quickly tab back into the game when you run p2press start because those controller presses only go to the active screen - I'd recommend joining the discord server too if you need any more help with setup

**Comment by robot-rover** [comment]
where is the invite link posted?

**Comment by TheBlocks** [comment]
Discord - https://discord.gg/q9pbsWz

**Comment by drssoccer55** [comment]
Vjoy no longer used in v3.
