### ISSUE TITLE
Why even bother with Cheat Engine and manual updating of addresses?

### ISSUE THREAD

**Issue by ccman32** [drssoccer55/RLBot#15]
I know that this isn't really an issue but I don't know where else I should write this.
I just randomly found this project yesterday and after looking at this project I noticed that it seems to be using hardcoded addresses and offsets to read information from the game client.
However, doing this is absolutely not necessary!
Since Rocket League was made using the Unreal Engine 3, all the information about classes/structures of the game are available in the game client.
There is a very informative tutorial & source code about how to reverse the core structures of the game and then use that information to generate an SDK for the game here: https://www.unknowncheats.me/forum/unreal-engine-3-a/71911-thefeckless-ue3-sdk-generator.html

Since I already have those engine structures, I'm willed to share that information so this framework can be improved.

**Comment by drssoccer55** [comment]
Yes we are already doing that actually to improve the framework but it has been slow from people being busy and code being private.  Join the discord here: https://discord.gg/zbaAKPt  You might be able to help out.

**Comment by ccman32** [comment]
Thank you for your reply. I just joined there so I guess this "issue" can be closed.
