### ISSUE TITLE
Having issues getting p2PressStart.py working.

### ISSUE THREAD

**Issue by badcoding101** [drssoccer55/RLBot#19]
Hi,

I am a very very novice coder (2 semesters of matlab) but i am trying to learn more and i thought this would be a perfect way to do so. But when i run p2PressStart.py in Thonny I get back an error stating
>>> %cd 'C:\RLbot\Python'
>>> %Run p2PressStart.py
Traceback (most recent call last):
  File "C:\RLbot\Python\p2PressStart.py", line 1, in <module>
    import pyvjoy
ModuleNotFoundError: No module named 'pyvjoy'
>>> 

But I dont know what I have done wrong. I have a pyvjoy folder with the address: C:\RLbot\Python\Python36-32\Lib\site-packages\pyvjoy

Any ideas on what could be causing this error?

**Comment by tarehart** [comment]
I'm not sure, but you can get better support by asking in the discord: https://discord.gg/5cNbXgG

**Comment by drssoccer55** [comment]
Yupp I second joining the discord for help.  Not sure where your python install(s) is/are but sounds like it could just be a misplaced install.

**Comment by drssoccer55** [comment]
No longer relevant in v3
