### ISSUE TITLE
Any plans for smarter bots?

### ISSUE THREAD

**Issue by AdityaAnand1** [drssoccer55/RLBot#25]
[This](https://www.reddit.com/r/RocketLeague/comments/7fwk2y/psyonix_can_we_please_get_some_better_bots_i_cant/) interesting reddit thread led me here and this repo looks very exciting!

I was just wondering what future direction you're thinking of for this project... Any plans for smarter (harder) bots?

**Comment by TheBlocks** [comment]
This framework allows people to make custom bots in Rocket League, and the bots are only getting better. The bot tournament last month was awesome, and there's a tournament coming up in February as well.

**Comment by drssoccer55** [comment]
Best place to keep up is the discord: https://discord.gg/zbaAKPt

I'm working on a bot myself that I am optimistic about but it'll be a while before it is ready.  There is already a bot that is nearly at all-star level.
