### ISSUE TITLE
Updates breaking this?

### ISSUE THREAD

**Issue by HaydenMeloche** [drssoccer55/RLBot#7]
Hi,

First of all really neat idea :smile: 

I'm one of the devs behind alphaconsole and I saw that your currently using mem pointers for editing. Alphaconsole used to do that as well and every semi-large update changes all the pointers and would screw us up (Even some pointers for most people wouldn't work for a few select people). So do you have a special way of handling this or do you have to re-find all of the pointers for RLbot?

**Comment by drssoccer55** [comment]
We are working on changing this to dll injection.  Join the discord if you want to keep up with what's happening! https://discord.gg/zbaAKPt

**Comment by HaydenMeloche** [comment]
Sounds good. GL with the SDK!
